---

- name: Check if rustup is already installed
  ansible.builtin.command:
    argv:
      - which
      - rustup
  register: check_rust
  changed_when: false
  failed_when: check_rust.rc not in [0,1]

- name: Install rust
  when: check_rust.rc != 0
  ansible.builtin.include_tasks:
    file: install.yml