---
# Installs the AWS cli v2

- name: Check if AWS cli is already installed
  ansible.builtin.command:
    argv:
      - which
      - aws
  register: check_aws
  changed_when: false
  failed_when: check_aws.rc not in [0,1]

- name: Install or update AWS cli v2
  when: aws_cli_update or check_aws.rc != 0
  block:
    - name: Ensure install and bin dirs are created
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        - "{{ aws_cli_install_dir }}"
        - "{{ aws_cli_bin_dir }}"

    - name: Download awscli v2
      ansible.builtin.unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        remote_src: true
        dest: "{{ temp_folder }}"

    - name: Install awscli v2
      ansible.builtin.command:
        argv:
          - "{{ temp_folder }}/aws/install"
          - --install-dir
          - "{{ aws_cli_install_dir }}"
          - --bin-dir
          - "{{ aws_cli_bin_dir }}"
      register: install_aws
      changed_when: install_aws.rc == 0
      failed_when: install_aws.rc != 0

    - name: Cleanup temp folder
      ansible.builtin.file:
        path: "{{ temp_folder }}/aws"
        state: absent