---
- src: stefangweichinger.ansible_rclone
- src: do1jlr.restic
  version: v0.7.1
- src: gantsign.golang
  version: 3.0.1
- src: hifis.unattended_upgrades
  version: v1.12.2
- src: gantsign.git_credential_manager
  version: 2.1.0