---

- name: Add user to groups
  ansible.builtin.user:
    append: true
    groups: "{{ add_groups }}"
    user: "{{ user }}"
  become: true

- name: Install dotfiles
  ansible.builtin.import_tasks:
    file: dotfiles.yml
  vars:
    repo_path: "{{ dev_folder }}/{{ dotfiles_repo_name }}"