---

- name: Add user to groups
  ansible.builtin.user:
    append: true
    groups: "{{ add_groups }}"
    user: "{{ user }}"
  become: true

# - name: Create dev folder
#   ansible.builtin.file:
#     path: "{{ dev_folder }}"
#     state: directory

# - name: Install repos
#   include_tasks: repos.yml
#   loop: "{{ repos }}"