---

- name: Remove unwanted apt packages
  ansible.builtin.apt:
    name: "{{ apt_packages_remove }}"
    state: absent
    clean: true
    purge: true

- name: Install apt packages
  ansible.builtin.apt:
    name: "{{ apt_packages_install }}"
    state: present
    update_cache: true

- name: Install apt packages from external repos
  ansible.builtin.include_role:
    name: apt-external
  loop: "{{ apt_packages_external }}"