- name: Handle non-ppa repos
  when: item.pubkey is defined
  vars:
    keyring_file: "{{ apt_keyring }}/{{ item.pubkey.filename }}"
  block:
    - name: Add "{{ item.name }}" GPG key
      ansible.builtin.get_url:
        url: "{{ item.pubkey.url }}"
        dest: "{{ keyring_file }}"

    - name: Add "{{ item.name }}" repo
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ arch }} signed-by={{ keyring_file }}] {{ item.repo }}"
        filename: "{{ item.name }}"
        state: present
        update_cache: true

    - name: Add "{{ item.name }}" src repo
      ansible.builtin.apt_repository:
        repo: "deb-src [arch={{ arch }} signed-by={{ keyring_file }}] {{ item.repo }}"
        filename: "{{ item.name }}"
        state: present
        update_cache: true
      when: item.src is defined

- name: Add "{{ item.name }}" PPA
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.name }}"
    state: present
    update_cache: true
  when: item.pubkey is not defined

- name: Install "{{ item.name }}" packages
  ansible.builtin.apt:
    name: "{{ item.pkgs }}"
    state: present