- name: Load values
  include_vars:
    file: binary.yml
    name: binary

- name: Create local bin folder
  ansible.builtin.file:
    path: "{{ local_bin }}"
    state: directory
    mode: 0755

- name: Download "{{ item.name }}" binary
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest | default(local_bin) }}/{{ item.name }}"
    mode: 0755
  loop: "{{ binary.install }}"

# restic and rclone are special cases cause they put version numbers in filenames AND they zip things

- block:
    - name: Install rclone
      ansible.builtin.include_role:
        name: stefangweichinger.ansible_rclone
      vars:
        install_manpages: false

    - name: Install restic
      ansible.builtin.include_role:
        name: do1jlr.restic
      vars:
        restic_version: "{{ binary.restic.version }}"
  become: true

# - name: Download and extract restic
#   ansible.builtin.unarchive:
#     src: "{{ binary.restic.url }}"
#     remote_src: true
#     dest: "{{ usr_local_bin }}"
#     mode: 0755
#     extra_opts:
#       - --transform
#       - s/^restic_{{ binary.restic.version }}_linux_amd64/restic

# - name: Download and extract rclone
#   ansible.builtin.unarchive:
#     src: "{{ binary.rclone.url }}"
#     remote_src: true
#     dest: "{{ usr_local_bin }}"
#     mode: 0755
#     include:
#       - rclone-*-linux-amd64/rclone