# Software that requires custom install steps and doesn't fall into one of the other categories

- name: Download awscli v2
  ansible.builtin.unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    remote_src: true
    dest: /tmp

- name: Install awscli v2
  ansible.builtin.command:
    cmd: /tmp/aws/install
    argv:
      - --install-dir
      - "{{ aws.cli.install_dir }}"
      - --bin-dir
      - "{{ aws.cli.bin_dir }}"
      - "{{ '--update' if aws.cli.update else omit }}"

- name: Cleanup temp folder
  ansible.builtin.file:
    path: /tmp/aws
    state: absent

- name: Install Go
  ansible.builtin.include_role:
    name: gantsign.golang
  vars:
    golang_install_dir: "{{ home }}/opt/go"
