---
# Manage installation of various packages

- become: true
  block:
    - name: Manage snaps
      ansible.builtin.import_tasks: snap.yml

    - name: Manage debs
      ansible.builtin.import_tasks: apt.yml

- name: Manage flatpaks
  ansible.builtin.import_tasks: flatpak.yml

- name: Manage pipx
  ansible.builtin.import_tasks: pipx.yml

# - name: Manage AppImages
#   ansible.builtin.include_tasks: appimage.yml