- block:
    - name: Manage debs
      include_tasks: apt.yml

    - name: Manage snaps
      include_tasks: snap.yml
  become: true

- name: Manage flatpaks
  include_tasks: flatpak.yml

- name: Manage binaries
  include_tasks: binary.yml

- name: Manage pipx
  include_tasks: pipx.yml

- name: Manage AppImages
  include_tasks: appimage.yml

- name: Manage custom
  include_tasks: custom.yml