- name: Load values
  include_vars:
    file: pipx.yml
    name: pipx

- name: Install pipx
  ansible.builtin.pip:
    name: pipx
    state: present

- name: Install pipx packages
  community.general.pipx:
    name: "{{ pipx.install }}"
    state: present