---

- name: Install pipx
  ansible.builtin.pip:
    name: pipx
    state: present

- name: Install pipx packages
  community.general.pipx:
    name: "{{ item }}"
    state: present
    install_deps: true
  loop: "{{ pipx_install }}"