- name: Download and extract latest restic release
  ansible.builtin.unarchive:
    src: "{{ url }}"
    dest: "{{ temp_folder }}"
    remote_src: true

- name: Move restic binary to "{{ bin_folder}}"
  ansible.builtin.copy:
    src: "{{ temp_folder }}/{{ asset_name }}"
    dest: "{{ bin_folder }}/restic"
    mode: "{{ permissions }}"
  become: true

- name: Cleanup temp folder
  ansible.builtin.file:
    path: "{{ temp_folder }}/{{ asset_name }}"
    state: absent