---
flatpak:
  install:
    - com.bitwarden.desktop
    - com.discordapp.Discord
    - com.getpostman.Postman
    - com.github.Eloston.UngoogledChromium
    - com.github.iwalton3.jellyfin-media-player
    - com.github.tchx84.Flatseal
    - com.github.xournalpp.xournalpp
    - com.jgraph.drawio.desktop
    - com.makemkv.MakeMKV
    - com.nextcloud.desktopclient.nextcloud
    - com.obsproject.Studio
    - com.valvesoftware.Steam
    - net.lutris.Lutris
    - org.flameshot.Flameshot
    - org.kde.filelight
    - org.kde.kid3
    - org.kde.kolourpaint
    - org.libreoffice.LibreOffice
    - org.mozilla.firefox
    - org.signal.Signal
    - org.videolan.VLC
    - rest.insomnia.Insomnia