- name: Install docker
  ansible.builtin.import_role:
    name: apt-external
  vars:
    item: "{{ docker_spec }}"

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: true
  become: true