---

- name: Ensure dev folder is created
  ansible.builtin.file:
    path: "{{ dev_folder }}"
    state: directory

- name: Clone settings repo
  ansible.builtin.git:
    repo: "{{ settings_repo_url }}"
    dest: "{{ dev_folder }}/{{ settings_repo_name }}"

- name: Link starship.toml
  ansible.builtin.file:
    path: "{{ home_folder }}/{{ starship_settings_path }}"
    src: "{{ dev_folder }}/{{ settings_repo_name }}/{{ starship_settings_path }}"
    state: link
    force: true