---

- name: Check if "{{ item.name }}" already exists
  ansible.builtin.command:
    argv:
      - which
      - "{{ item.name }}"
  register: result
  changed_when: false
  failed_when: result.rc not in [0,1]

- name: Install "{{ item.name }}"
  when: result.rc != 0
  block:
    - name: Ensure "{{ item.bin_folder }}" is created
      ansible.builtin.file:
        path: "{{ item.bin_folder }}"
        state: directory
        mode: 0755

    - name: Download latest "{{ item.name }}" release to "{{ item.bin_folder }}"
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ item.bin_folder }}/{{ item.name }}"
        mode: 0755