---
# Handles installing standalone binaries

- name: Install binaries
  ansible.builtin.include_tasks:
    file: install.yml
  loop: "{{ bin_install }}"

- name: Install rclone
  ansible.builtin.import_role:
    name: stefangweichinger.ansible_rclone

- name: Install restic
  ansible.builtin.import_role:
    name: do1jlr.restic