- become: true
  block:
    - name: Initial tasks
      ansible.builtin.import_tasks:
        file: pre.yml

    - name: Add non-ppa repo ("{{ item.name }}")
      when: item.pubkey is defined
      vars:
        keyfile: "{{ apt.keyrings.path }}/{{ item.pubkey.filename }}"
      ansible.builtin.include_tasks:
        file: non-ppa.yml

    - name: Add PPA ("{{ item.name }}")
      when: item.pubkey is not defined
      ansible.builtin.apt_repository:
        repo: "{{ item.repo }}"
        state: present
        update_cache: true

    - name: Install packages ("{{ item.name }}")
      ansible.builtin.apt:
        name: "{{ item.packages }}"
        state: present
      notify: "{{ item.handlers if item.handlers is defined else omit }}"