- become: true
  block:
    - name: Install dependencies ("{{ name }}")
      when: dependencies is defined
      ansible.builtin.apt:
        name: "{{ dependencies }}"
        state: present
        update_cache: true

    - name: Ensure apt keyrings folder is created
      ansible.builtin.file:
        path: "{{ apt.keyrings.path }}"
        state: directory
        mode: "{{ apt.keyrings.perms.folder }}"

    - name: Add non-ppa repo ("{{ name }}")
      when: pubkey is defined
      vars:
        keyfile: "{{ apt.keyrings.path }}/{{ pubkey.filename }}"
      block:
        - name: Add repo GPG key ("{{ name }}")
          ansible.builtin.get_url:
            url: "{{ pubkey.url }}"
            dest: "{{ keyfile }}"
            mode: "{{ apt.keyrings.perms.file }}"

        - name: Add repo ("{{ name }}")
          ansible.builtin.apt_repository:
            repo: "deb [arch={{ arch }} signed-by={{ keyfile }}] {{ repo.url }} {{ repo.branch }}"
            state: present
            update_cache: true

        - name: Add src repo ("{{ name }}")
          when: repo.src is defined
          ansible.builtin.apt_repository:
            repo: "deb-src [arch={{ arch }} signed-by={{ keyfile }}] {{ repo.url }} {{ repo.branch }}"
            state: present
            update_cache: true

    - name: Add PPA ("{{ name }}")
      when: pubkey is not defined
      ansible.builtin.apt_repository:
        repo: "{{ repo.url }}"
        state: present
        update_cache: true

    - name: Install packages ("{{ name }}")
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present