- name: Install dependencies for "{{ item.name }}"
  when: item.dependencies is defined
  ansible.builtin.apt:
    name: "{{ item.dependencies }}"
    state: present
    update_cache: true

- name: Ensure apt keyrings folder is created
  ansible.builtin.file:
    path: "{{ apt_keyrings_path }}"
    state: directory
    mode: "{{ apt_keyrings_permissions_folder }}"
    owner: root
    group: root